Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UploadExcelFile.Models
{
    public class Contact
    {
		public int ContactID { get; set; }

		[Required]
		public string FirstName { get; set; }

		[Required]
		public string LastName { get; set; }

		[Required]
		public string Email { get; set; }

		public string Telephone { get; set; }

		[Required]
		public string Mobile { get; set; }

		[Required]
		public int CompanyID { get; set; }

		public string Address1 { get; set; }

		public string Address2 { get; set; }

		public string CityTown { get; set; }

		public string StateCounty { get; set; }

		public string PostCode { get; set; }

		public string Country { get; set; }

		public string CustomField1 { get; set; }

		public string CustomField2 { get; set; }

		public DateTime CustomDate { get; set; }
	}
}

Controllers/ContactBatchController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;
using System.Web.SessionState;
using UploadExcelFile.Models;

namespace UploadExcelFile.Controllers
{
    [SessionState(SessionStateBehavior.Required)]
    public class ContactBatchController : Controller
    {
        // GET: ContactBatch
        public ActionResult Index()
        {
            List<ContactBatch> contactBatchDBs = new List<ContactBatch>();
            contactBatchDBs = ContactBatchDB.GetAllBatches();
            return View(contactBatchDBs);
        }

        [HttpGet]
        public ActionResult GetFileById(int id)
        {
            List<ContactVM> contactVM = new List<ContactVM>();
            contactVM = ContactBatchDB.GetContactByBatchId(id);
            return View(contactVM);
        }
        
        [HttpGet]
        public ActionResult DeleteById(int id)
        {
            List<ContactVM> contactVM = new List<ContactVM>();
            contactVM = ContactBatchDB.DeleteContactByBatchId(id);
            return View(contactVM);
        }

        [HttpGet]
        public ActionResult DeletedBatchById(int id)
        {
            ContactBatchDB.DeleteFileByBatchId(id);
            return View();
        }

        [HttpGet]
        [WebMethod(EnableSession = true)]
        public ActionResult EditById(int id)
        {
            List<ContactVM> contactVM = new List<ContactVM>();
            contactVM = ContactBatchDB.EditContactByBatchId(id);
            Session["BatchId"] = ContactBatchDB.EditContactByBatchId(id);
            return View(contactVM);
        }

        [HttpGet]
        public ActionResult ReUploadBatch()
        {
            return View(new List<ContactVM>());
        }

        [HttpPost]
        [WebMethod(EnableSession = true)]
        public ActionResult ReUploadBatch(HttpPostedFileBase postedFile)
        {
            List<ContactVM> contact = new List<ContactVM>();
            string filePath = string.Empty;
            if (postedFile != null)
            {
                try
                {
                    string path = Server.MapPath("~/Uploads/");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    filePath = path + Path.GetFileName(postedFile.FileName);
                    string extension = Path.GetExtension(postedFile.FileName);
                    postedFile.SaveAs(filePath);

                    //Read the contents of CSV file.
                    string csvData = System.IO.File.ReadAllText(filePath);

                    //Execute a loop over the rows.
                    foreach (string row in csvData.Split('\n'))
                    {
                        if (!string.IsNullOrEmpty(row))
                        {
                            ContactVM contactVM = new ContactVM();

                            contactVM.FirstName = row.Split(',')[0];
                            contactVM.LastName = row.Split(',')[1];
                            contactVM.Email = row.Split(',')[2];
                            contactVM.Telephone = row.Split(',')[3];
                            contactVM.Mobile = row.Split(',')[4];
                            contactVM.CompanyID = Convert.ToInt32(row.Split(',')[5]);

                            //Checking then first Name field
                            if (contactVM.FirstName == string.Empty)
                            {
                                contactVM.Status = "Invalid";
                                contactVM.Reason = "First Name field is required";
                            }

                            //checking the Last Name field
                            if (contactVM.LastName == string.Empty)
                            {
                                contactVM.Status = "Invalid";
                                contactVM.Reason = "Last Name field is required";
                            }

                            //checking for email field
                            if (contactVM.Email == string.Empty)
                            {
                                contactVM.Status = "Invalid";
                                contactVM.Reason = "Email field is required";
                            }

                            //checking for Mobile
                            if (contactVM.Mobile == string.Empty)
                            {
                                contactVM.Status = "Invalid";
                                contactVM.Reason = "Mobile field is required";
                            }

                            //checking for Valid Company Id
                            if (contactVM.CompanyID != 7)
                            {
                                contactVM.Status = "Invalid";
                                contactVM.Reason = "Invalid Company iD";
                            }

                            contact.Add(contactVM);
                        }
                    }
                }
                catch (Exception ex)
                {
                    TempData["Message"] = "No File Chosen";
                    TempData["Message"] = "Something went wrong " + ex.Message;
                }
            }
            //Seession object
            Session["ReUploadBatch"] = contact;

            return View(contact);
        }

        [HttpGet]
        [WebMethod(EnableSession = true)]
        public ActionResult UpdateByBatchId(ContactVM contactVM)
        {
            int batchID = 0;
            List<ContactVM> batchId = new List<ContactVM>();
            batchId = (List<ContactVM>)Session["BatchId"];
            foreach(ContactVM contactsBatch in batchId)
            {
                batchID = contactsBatch.BatchId;
            }
            
            //Session object
            List<ContactVM> contacts = new List<ContactVM>();
            contacts = (List<ContactVM>)Session["ReUploadBatch"];

            ContactBatchDB.UpdateContactByBatchId(contacts, batchID);

            return View();
        }
    }
}

Controllers/ContactsController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UploadExcelFile.Models;
using System.Web.SessionState;
using System.Web.Services;
using System.Data;
using System.Data.SqlClient;

namespace UploadExcelFile.Controllers
{
    [SessionState(SessionStateBehavior.Required)]
    public class ContactsController : Controller
    {
        // GET: Contacts
        [HttpGet]
        public ActionResult Index()
        {
            Session.Clear();
            return View(new List<ContactVM>());
        }

        //POST: Contacts
        [HttpPost]
        [WebMethod(EnableSession = true)]
        public ActionResult Index(HttpPostedFileBase postedFile)
        {
            List<ContactVM> contact = new List<ContactVM>();
            string filePath = string.Empty;
            if (postedFile != null)
            {
                try
                {
                    string path = Server.MapPath("~/Uploads/");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    filePath = path + Path.GetFileName(postedFile.FileName);
                    string extension = Path.GetExtension(postedFile.FileName);
                    postedFile.SaveAs(filePath);

                    //Read the contents of CSV file.
                    string csvData = System.IO.File.ReadAllText(filePath);

                    //Execute a loop over the rows.
                    foreach (string row in csvData.Split('\n'))
                    {
                        if (!string.IsNullOrEmpty(row))
                        {
                            ContactVM contactVM = new ContactVM();

                            contactVM.FirstName = row.Split(',')[0];
                            contactVM.LastName = row.Split(',')[1];
                            contactVM.Email = row.Split(',')[2];
                            contactVM.Telephone = row.Split(',')[3];
                            contactVM.Mobile = row.Split(',')[4];
                            contactVM.CompanyID = Convert.ToInt32(row.Split(',')[5]);

                            //Checking then first Name field
                            if (contactVM.FirstName == string.Empty)
                            {
                                contactVM.Status = "Invalid";
                                contactVM.Reason = "First Name field is required";
                            }

                            //checking the Last Name field
                            if (contactVM.LastName == string.Empty)
                            {
                                contactVM.Status = "Invalid";
                                contactVM.Reason = "Last Name field is required";
                            }
                            
                            //checking for email field
                            if (contactVM.Email == string.Empty)
                            {
                                contactVM.Status = "Invalid";
                                contactVM.Reason = "Email field is required";
                            }

                            //checking for Mobile
                            if (contactVM.Mobile == string.Empty)
                            {
                                contactVM.Status = "Invalid";
                                contactVM.Reason = "Mobile field is required";
                            }

                            //checking for Valid Company Id
                            if (contactVM.CompanyID != 7)
                            {
                                contactVM.Status = "Invalid";
                                contactVM.Reason = "Invalid Company iD";
                            }

                            contact.Add(contactVM);
                        }
                    }
                }
                catch (Exception ex)
                {
                    TempData["Message"] = "No File Chosen";
                    TempData["Message"] = "Something went wrong " + ex.Message;
                }
            }
            //Seession object
            Session["Upload"] = contact;

            return View(contact);
        }

        //Post Method to the Database
        [HttpGet]
        [WebMethod(EnableSession = true)]
        public ActionResult ContactsTable()
        {
            DateTime myDateTime = DateTime.Now;
            string sqlformattedDate = myDateTime.ToString("yyyy-MM-dd hh:mm:ss.fff");
            string batchName = GetBatchName();
            //Creating a new Batch object
            ContactBatch batch = new ContactBatch();
            batch.BatchName = batchName;
            batch.CreatedBy = "System";
            batch.DateCreated = Convert.ToDateTime(sqlformattedDate);

            //calling the post to ContactBatch table--
            int batchID = ContactDB.GetBatchID(batch);

            List<ContactVM> contacts = new List<ContactVM>();
            contacts = (List<ContactVM>)Session["Upload"];
            ContactDB.PostToDatabase(contacts, batchID);
            return View(contacts);
        }

        private string GetBatchName()
        {
            string batchName;
            var rand = new Random();
            ContactBatch batch = new ContactBatch();
            var newRand = rand.Next(100);

            batchName = batch.BatchName = "Upload - " + newRand;

            return batchName;
        }
    }
}

Views/Contacts/ContactsTable.cshtml
@using UploadExcelFile.Models
@model IEnumerable<ContactVM>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">

<style>
    body {
        text-align: center;
        padding: 40px 0;
        background: #EBF0F5;
    }

    h1 {
        color: #88B04B;
        font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
        font-weight: 900;
        font-size: 40px;
        margin-bottom: 10px;
    }

    p {
        color: #404F5E;
        font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
        font-size: 20px;
        margin: 0;
    }

    i {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left: -15px;
    }

    .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
    }
</style>


@{
    int contactCount = 0;
}

@foreach (ContactVM contact in Model)
{
    contactCount = contactCount + 1;
}

<div class="card">
    <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
    </div>
    <h1>Success</h1>
    <p class="text-success">@contactCount Contacts Added To The Database Successfully</p>
</div>

<hr />
@*<table cellpadding="0" cellspacing="0" border="1" class="table table-bordered">
        <tr>
            <td>FirstName</td>
            <td>LastName</td>
            <td>Email</td>
            <td>Telephone</td>
            <td>Mobile</td>
            <td>CompanyID</td>
        </tr>

        @{
            int contactCount = 0;
        }

        @foreach (ContactVM contact in Model)
        {
            <tr>
                <td>@contact.FirstName</td>
                <td>@contact.LastName</td>
                <td>@contact.Email</td>
                <td>@contact.Telephone</td>
                <td>@contact.Mobile</td>
                <td>@contact.CompanyID</td>
            </tr>

            contactCount = contactCount + 1;
        }
    </table>*@

<button class="btn btn-default">
    @Html.ActionLink("Back To Home", "Index", "Contacts")
</button>

Views/Contacts/Index.cshtml
@using UploadExcelFile.Models
@model IEnumerable<ContactVM>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 style="color: red;"><strong>@TempData["Message"]</strong></h3>
<h3 style="color: green;"><strong>@TempData["Message2"]</strong></h3>

@{
    string display = "Valid";

    bool displayImport = true;
}

@if (Model.Count() > 0)
{
    <hr />
    <table class="table table-bordered" cellpadding="0" cellspacing="0" border="1">
        <tr>
            <td><strong>FirstName</strong></td>
            <td><strong>LastName</strong></td>
            <td><strong>Email</strong></td>
            <td><strong>Telephone</strong></td>
            <td><strong>Mobile</strong></td>
            <td><strong>CompanyID</strong></td>
            <td><strong>Status</strong></td>
            <td><strong>Reason</strong></td>
        </tr>
        @foreach (ContactVM contact in Model)
        {
            <tr>
                <td>@contact.FirstName</td>
                <td>@contact.LastName</td>
                <td>@contact.Email</td>
                <td>@contact.Telephone</td>
                <td>@contact.Mobile</td>
                <td>@contact.CompanyID</td>
                <td>@contact.Status</td>
                <td style="color:red">@contact.Reason</td>

            </tr>
        }

    </table>

    foreach (ContactVM conntact in Model)
    {

        display = conntact.Status;
    }

    if (display != "Invalid")
    {
        <button class="btn btn-default">
            @Html.ActionLink("Submit", "ContactsTable", "Contacts")
        </button>

        displayImport = false;
    }


}


<form asp-controller="Contacts" asp-action="Index" method="Post" enctype="multipart/form-data">

    @if (displayImport == true)
    {
        <input class="form-control" type="file" name="postedFile" />
        <hr />
        <input type="submit" value="Validate" class="btn btn-primary" />
        // display = "Valid";

    }
    @if (display == "Invalid")
    {
        <h3 style="color:red">Please fill missing field and re-import file</h3>
    }


</form>
<br />
<button class="btn btn-default">
    <span style="color:white">@Html.ActionLink("View Batches", "Index", "ContactBatch")</span>
</button>

@*<br />
    <br />
    <form asp-controller="Contacts" asp-action="Index" method="Post" enctype="multipart/form-data">
        <input type="file" name="postedFile" />
        <hr />
        <input id="import" type="submit" value="import" />
        <input type="reset" value="Cancel" style="margin-left:527px;" />
    </form>*@